### ISSUE TITLE
Controller has error "secrets \"cloud-credentials\" already exists" several times during migration

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#107]
Have been seeing several instances of `"cloud-credentials" already exists` in rapid succession during migrations recently. @jortel I think this is an unintended side-effect of the ensureStorage pieces that have recently been added. 

I've never seen this block a migration, but would be nice to fix the underlying issue or silence the error message if we don't care about it.

```
{"level":"info"
"ts":1558560519.166244
"logger":"cluster|6fd7s"
"msg":"[rWatch] Starting manager"}


{"level":"info"
"ts":1558560519.1662652
"logger":"cluster|6fd7s"
"msg":"[rWatch] Manager started"}


{"level":"info"
"ts":1558560519.1662774
"logger":"cluster|6fd7s"
"msg":"Remote watch started."
"cluster":"migcluster-local"}


{"level":"error"
"ts":1558560525.3750854
"logger":"kubebuilder.controller"
"msg":"Reconciler error"
"controller":"migplan-controller"
"request":"mig/migplan-sample"
"error":"secrets \"cloud-credentials\" already exists"
"stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128
github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:217
github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until
	/home/dwhatley/dev/GO/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

```

**Comment by djwhatle** [comment]
@jortel To provide some more context, I see this error message spammed ~10 times during controller startup, specifically while the remotewatch against the local cluster is in the process of being created. The error messages stop when creation of the remotewatch finishes.

Jeff, I heard you weren't seeing this in your controller. I wonder if this reproducer case would make it visible. I'm on OCP 4->4 for this test setup.

**Comment by pranavgaikwad** [comment]
> @jortel To provide some more context, I see this error message spammed ~10 times during controller startup, specifically while the remotewatch against the local cluster is in the process of being created. The error messages stop when creation of the remotewatch finishes.
> 
> Jeff, I heard you weren't seeing this in your controller. I wonder if this reproducer case would make it visible. I'm on OCP 4->4 for this test setup.

I am seeing the exact same errors. I am on OCP 3 -> 4

**Comment by dipak-pawar** [comment]
I am also facing the same issue

**Comment by jortel** [comment]
Fixed by: https://github.com/fusor/mig-controller/pull/145
