### ISSUE TITLE
Is it correct to create initial cloud credentails with no keys in them with deploy script?

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-controller#110]
Possibly related to #107, but I noticed [the deploy script](https://github.com/fusor/mig-controller/blob/master/hack/deploy/deploy_velero.sh#L12) for velero creates some initial cloud credentials with a secret that decodes to:

```
[default]
aws_access_key_id=
aws_secret_access_key=
```

Shouldn't the controller check for the presence of this, and if it doesn't already exist, create it? Why create empty credentials?

**Comment by djwhatle** [comment]
@eriknelson I think I did this to stop Velero pod from failing to start due to failed mount of the cloud-credentials secret if it doesn't exist.

**Comment by eriknelson** [comment]
Oh wow, so Velero's pod won't run unles that secret exists?

**Comment by djwhatle** [comment]
@eriknelson if I had commented out the cloud-credentials secret mount I think the pod would have started without an issue. The thing is, mig-controller doesn't modify the Velero deployment, it just assumes Velero is pointed at the cloud-credentials secret and overwrites the contents of that secret.
