### ISSUE TITLE
Transient "MigPlan not ready" when migration is running

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#120]
Was running a MigMigration and noticed a status condition "MigPlan is not ready" pop up  on the MigMigration status a few times for a few seconds each time during the Migration. Not sure what caused this (and it didn't cause any real problems for me) but wanted to document in case this is an issue later.

I didn't isolate this all the way down the chain, it disappeared very quickly.

**Comment by jortel** [comment]
Fixed by: https://github.com/fusor/mig-controller/pull/141
