### ISSUE TITLE
Travis should be setup to gate PRs on test and style

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-controller#127]
It's good practice to gate PR acceptance on travis runs (or any CI for that matter) prior to acceptance. We spent some time on this in CPMA, the `make ci` target is particularly useful. It ensures the code is formatted according to expectations, code builds, and tests are green, and because it's a make target, devs can (should) run it before any submissions (https://github.com/fusor/cpma/blob/master/Makefile#L25). This isn't based on any violations I've seen, it's just a practice that's served us nicely, especially when/if we start to receive community submissions.

**Comment by jortel** [comment]
@eriknelson, I believe this issue has been resolved.  https://github.com/fusor/mig-controller/blob/master/.travis.yml.  Please close if you agree.
