### ISSUE TITLE
Selinux issues with Velero restic pod on Openshift 4

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#143]
From @jmontleon and @dymurray investigations

Velero's restic implementation mounts the 'pods' directory to do backups 
and restores.

In Openshift 3 this directory is at 
/var/lib/origin/openshift.local.volumes/pods/ and has a selinux context 
of system_u:object_r:container_file_t:s0.

In Openshift 4 the directory is now in the default location for 
Kubernetes /var/lib/kubelet/pods which is not a problem, but the selinux 
context now appears to default to system_u:object_r:var_lib_t:s0.

---
Running privileged seems to get us working, need to learn if there is a better path forward.

`oc adm policy add-scc-to-user privileged system:serviceaccount:velero:velero`

oc patch -n velero ds restic -p 
'{"spec":{"template":{"spec":{"containers":[{"name": "velero", 
"securityContext":{"privileged":true}}]}}}}'

**Comment by jwmatthews** [comment]
Related to https://github.com/fusor/mig-controller/pull/139

**Comment by jwmatthews** [comment]
@rhatdan @mrunalp

We hit a SELinux issue as described in original comment.
Our current workaround is to run as 'privileged'.

Do you know of a better solution?  Any tips of who we should work with to improve?
This is for OCP 3 to 4 Migrations.

**Comment by jwmatthews** [comment]
@dymurray pointed out that the official Velero/Restic docs are recommending to run 'privileged' or to create a custom SCC.

https://github.com/heptio/velero/blob/master/site/docs/master/restic.md#instructions

**Comment by rhatdan** [comment]
Do you want /var/lib/kubernetes with this label or /var/lib/kubernetes/pods?

Remember that all containers can read/write this label, so it should not be used too broadly.

**Comment by dymurray** [comment]
Closing this issue as it is a hard requirement that Restic runs in the privlieged SCC.
