### ISSUE TITLE
As part of PV discovery, show current storageClass, allow selection of storageClass on destination

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#178]
Goals:
 - Surface storageClass on PVs being migrated from source cluster in PV discovery output
 - Provide recommended storageClass mapping from source -> destination cluster where possible
 - Give user control over storageClass that will be used for dynamic storage provisioning on destination in 'copy' workflows

**Comment by jwmatthews** [comment]
Marking this as closed as @sseago added this behavior to the controller a few sprints back and we verified it working with Gluster->Ceph and NFS->Ceph migrations.
