### ISSUE TITLE
Make velero install namespace configurable

### ISSUE THREAD

**Issue by sseago** [fusor/mig-controller#183]
This is a long-term solution for https://github.com/fusor/mig-controller/issues/182

We should make the controller configurable to support a velero install dedicated to migration or a standard shared-with-normal-usage velero in the velero namespace.

The main things required for this:
- Replace the VeleroNamespace const with a VeleroNamespace parameter on MigCluster.Spec
- Conditionalize migration-specific actions in the migration plugin based on the presence of a flag annotation on the backup/restore CR ("openshift.io/is-migration" or something similar)
- Add the migration flag annotation to any backup/restore CRs created by the controller.

**Comment by jwmatthews** [comment]
Spoke with @sseago and @jmontleon about this today.  
Thinking is that for first release (alongside OCP 4.2) we proceed with issue #182 to ensure we have a known Velero with plugins we've qualified. 

In the future would be nice if we had more options to work with a given installed Velero instance on a cluster.  I view this enhancement as a post alongside 4.2 release.
