### ISSUE TITLE
cloud-credentials secret not being created or updated when a migstorage os created

### ISSUE THREAD

**Issue by jmontleon** [fusor/mig-controller#186]

**Comment by jmontleon** [comment]
Talked to @sseago  and he saw that it's also at least not updating. I don't ever even see cloud-credentials created when I create a migstorage item, let alone get updated.

**Comment by sseago** [comment]
So the reason mine wasn't updating was that the migplan wasn't ready, so it was working as designed. Once I resolved the migplan issue, the credentials are updating in response to changes to the migstorage resource as expected.

**Comment by sseago** [comment]
The velero cloud-credentials secret isn't updated until the migstorage resource is attached to a migplan, since the secret needs to be created in both the src and destination clusters, and without a migplan we don't know what those are yet.

**Comment by jmontleon** [comment]
This can be closed. It looks like it's working as intended.
