### ISSUE TITLE
Add a validation on MigPlan name:  Starting with a number is not allowed, example '0710a' used for plan name resulted in error

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#190]
I created the below, didn't realize it'd be a problem.   

```
$ oc get migplan 0710a -o yaml
apiVersion: migration.openshift.io/v1alpha1
kind: MigPlan
metadata:
  annotations:
    touch: ccd22062-2a42-4434-8fef-c36e93142611
  creationTimestamp: "2019-07-10T20:52:07Z"
  generation: 3
  name: 0710a
  namespace: mig
  resourceVersion: "146505"
  selfLink: /apis/migration.openshift.io/v1alpha1/namespaces/mig/migplans/0710a
  uid: 9485bd0a-a354-11e9-8773-063ca044fe88
spec:
  destMigClusterRef:
    name: host
    namespace: mig
  migStorageRef:
    name: jwms3
    namespace: mig
  namespaces:
  - mysql-persistent
  persistentVolumes:
  - action: copy
    capacity: 10Gi
    name: vol21
    pvc:
      Name: mysql
      Namespace: mysql-persistent
    supportedActions:
    - copy
    - move
  srcMigClusterRef:
    name: ocp3
    namespace: mig


```

$ oc logs controller-manager-79bf7cd7d-99sbr -n mig

`{"level":"error","ts":1562792358.9312413,"logger":"plan|wvc7f","msg":"","error":"Service \"0710a-registry-qqvq8\" is invalid: metadata.name: Invalid value: \"0710a-registry-qqvq8\": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.ensureRegistryService\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migplan/registry.go:198\ngithub.com/fusor/mig-controller/pkg/controller/migplan.ReconcileMigPlan.ensureMigRegistries\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migplan/registry.go:62\ngithub.com/fusor/mig-controller/pkg/controller/migplan.(*ReconcileMigPlan).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migplan/migplan_controller.go:174\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}`

**Comment by jortel** [comment]
Seems unnecessarily restrictive to the user for the controller to restrict the plan _name_.  Instead, let's update the controller to ensure the generated name is valid.

**Comment by eriknelson** [comment]
I was surprised to find this, since it's totally valid for a k8s name to start with a number. But when I went to test it, the migplan was confusingly without a status. Is this just a controller fix?
