### ISSUE TITLE
'unable to validate against any security context constraint' from a Stage of 'mysql' workload.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#191]
I deployed mysql from below into my Source Cluster:
https://raw.githubusercontent.com/fusor/ocp-mig-test-data/master/roles/pvc/mysql_pvc/files/mysql-persistent-template.yml

Saw below from mig-controller logs

`
{"level":"error","ts":1562801060.8079782,"logger":"migration|pssnv","msg":"","error":"pods \"mysql-1-x26sf\" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000060000}: 1000060000 is not an allowed group provider restricted: .spec.securityContext.seLinuxOptions.level: Invalid value: \"s0:c8,c2\": must be s0:c23,c7 spec.initContainers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c8,c2\": must be s0:c23,c7 spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000060000: must be in the ranges: [1000520000, 1000529999] spec.containers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c8,c2\": must be s0:c23,c7]","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:288\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:249\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:104\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
`

More Info

On Source Side:
```
$ oc get pod mysql-1-x26sf -o yaml -n mysql-persistent
apiVersion: v1
kind: Pod
metadata:
  annotations:
    openshift.io/deployment-config.latest-version: "1"
    openshift.io/deployment-config.name: mysql
    openshift.io/deployment.name: mysql-1
    openshift.io/scc: restricted
  creationTimestamp: "2019-07-10T18:48:01Z"
  generateName: mysql-1-
  labels:
    app: mysql
    deployment: mysql-1
    deploymentconfig: mysql
    name: mysql
  name: mysql-1-x26sf
  namespace: mysql-persistent
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicationController
    name: mysql-1
    uid: 3affd8f2-a343-11e9-94dc-0609d6689420
  resourceVersion: "96893"
  selfLink: /api/v1/namespaces/mysql-persistent/pods/mysql-1-x26sf
  uid: 3e35325d-a343-11e9-94dc-0609d6689420
spec:
  containers:
  - env:
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: database-user
          name: mysql
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-password
          name: mysql
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: database-root-password
          name: mysql
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          key: database-name
          name: mysql
    image: docker-registry.default.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
    imagePullPolicy: IfNotPresent
    name: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
    resources:
      limits:
        memory: 512Mi
      requests:
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - KILL
        - MKNOD
        - SETGID
        - SETUID
      runAsUser: 1000060000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/lib/mysql/data
      name: mysql-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-lhcql
      readOnly: true
  dnsPolicy: ClusterFirst
  imagePullSecrets:
  - name: default-dockercfg-g8d52
  nodeName: node1.jwm0710ocp3a.internal
  nodeSelector:
    node-role.kubernetes.io/compute: "true"
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000060000
    seLinuxOptions:
      level: s0:c8,c2
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  volumes:
  - name: mysql-data
    persistentVolumeClaim:
      claimName: mysql
  - name: default-token-lhcql
    secret:
      defaultMode: 420
      secretName: default-token-lhcql
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-10T18:48:01Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-10T18:48:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-10T18:48:01Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://f633d22f28a37b4620ce5de9ab01ec3191944ef6edf5834e6f047b60adec5d62
    image: docker-registry.default.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
    imageID: docker-pullable://docker-registry.default.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
    lastState: {}
    name: mysql
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2019-07-10T18:48:50Z"
  hostIP: 192.168.0.169
  phase: Running
  podIP: 10.1.6.7
  qosClass: Burstable
  startTime: "2019-07-10T18:48:01Z"
```

```
$ oc get deploymentconfigs mysql -n mysql-persistent -o yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{"template.alpha.openshift.io/wait-for-ready":"true"},"labels":{"app":"mysql"},"name":"mysql","namespace":"mysql-persistent"},"spec":{"replicas":1,"selector":{"name":"mysql"},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"mysql","name":"mysql"}},"spec":{"containers":[{"env":[{"name":"MYSQL_USER","valueFrom":{"secretKeyRef":{"key":"database-user","name":"mysql"}}},{"name":"MYSQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"database-password","name":"mysql"}}},{"name":"MYSQL_ROOT_PASSWORD","valueFrom":{"secretKeyRef":{"key":"database-root-password","name":"mysql"}}},{"name":"MYSQL_DATABASE","valueFrom":{"secretKeyRef":{"key":"database-name","name":"mysql"}}}],"image":" ","imagePullPolicy":"IfNotPresent","name":"mysql","ports":[{"containerPort":3306}],"resources":{"limits":{"memory":"512Mi"}},"volumeMounts":[{"mountPath":"/var/lib/mysql/data","name":"mysql-data"}]}],"volumes":[{"name":"mysql-data","persistentVolumeClaim":{"claimName":"mysql"}}]}},"triggers":[{"imageChangeParams":{"automatic":true,"containerNames":["mysql"],"from":{"kind":"ImageStreamTag","name":"mysql:5.7","namespace":"openshift"}},"type":"ImageChange"},{"type":"ConfigChange"}]}}
    template.alpha.openshift.io/wait-for-ready: "true"
  creationTimestamp: "2019-07-10T18:47:55Z"
  generation: 2
  labels:
    app: mysql
  name: mysql
  namespace: mysql-persistent
  resourceVersion: "60872"
  selfLink: /apis/apps.openshift.io/v1/namespaces/mysql-persistent/deploymentconfigs/mysql
  uid: 3afd607c-a343-11e9-94dc-0609d6689420
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    name: mysql
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
        name: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: mysql
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-root-password
              name: mysql
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: mysql
        image: docker-registry.default.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
        imagePullPolicy: IfNotPresent
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/mysql/data
          name: mysql-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - mysql
      from:
        kind: ImageStreamTag
        name: mysql:5.7
        namespace: openshift
      lastTriggeredImage: docker-registry.default.svc:5000/openshift/mysql@sha256:16386423eaa147384d3a9820f3eb47aa1e7b93570f4d577593931d1f0cf09176
    type: ImageChange
  - type: ConfigChange
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-07-10T18:48:51Z"
    lastUpdateTime: "2019-07-10T18:48:51Z"
    message: Deployment config has minimum availability.
    status: "True"
    type: Available
  - lastTransitionTime: "2019-07-10T18:48:52Z"
    lastUpdateTime: "2019-07-10T18:48:52Z"
    message: replication controller "mysql-1" successfully rolled out
    reason: NewReplicationControllerAvailable
    status: "True"
    type: Progressing
  details:
    causes:
    - type: ConfigChange
    message: config change
  latestVersion: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 0
  updatedReplicas: 1

```

**Comment by jwmatthews** [comment]
@sseago @pranavgaikwad should we track this issue in https://github.com/fusor/openshift-migration-plugin instead of here?

My initial thought is this might end up being a fix in a velero plugin

**Comment by pranavgaikwad** [comment]
@jwmatthews forgot about this issue until you emailed the other day. This looks like an issue with the app itself. @djwhatle saw a similar issue with MySQL app on his v4 cluster. Can you deploy the app on your destination cluster? If it works, then it could be a migration issue. We would then have to take care of it in the plugin. However, I have seen problems in general with the pods that require `privileged` or `anyuid`.

**Comment by djwhatle** [comment]
I have never seen this particular issue, at least not with SCC errors showing up in controller logs. 

I have seen issues with failure to start a mysql-persistent app on the destination side which I attributed to differences in the ServiceAccount used to run the mysql container on either side, but did not fully solve. 

Upon manual inspection of PV contents, it was possible to notice a difference in the UID/GID attached to the files generated on initial mysql setup depending on the SA / scc rules set.

**Comment by pranavgaikwad** [comment]
Not sure if #205 is related to this issue. Could be similar

**Comment by Danil-Grigorev** [comment]
@pranavgaikwad @jwmatthews The app deploys perfectly on any cluster version. Looks like the range for UIDs in `restricted` scc is different on v3 and v4, and it could happen that the values won't match after the migration. But in isolated deployment this is not the issue.

**Comment by dymurray** [comment]
I filed a duplicate of this issue here: https://github.com/fusor/mig-controller/issues/215

Was not repeatable for me but will keep trying to reproduce it.

**Comment by dymurray** [comment]
This is also breaking mediawiki as well. It runs in the `restricted` scc and has access rights problems on OCP 4 after migration.

**Comment by rpattath** [comment]
I was able to reproduce this during nginx app migration - NFS copy. Below are the log messages from the controller pod

{"level":"info","ts":1564434749.0223784,"logger":"migration|zb4w4","msg":"PVC annotations/labels removed.","ns":"nginx-example","name":"nginx-logs"}
{"level":"error","ts":1564434749.1045072,"logger":"migration|zb4w4","msg":"","error":"pods \"nginx-deployment-6c7958f7b7-nbctp-stage\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2 spec.initContainers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2 spec.containers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2]","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:302\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:263\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:367\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:76\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1564434749.104731,"logger":"migration|pvpl4","msg":"Migration [RUN]","name":"66274d10-b245-11e9-8131-af58191a2f8c","stage":true,"phase":"EnsureAnnotationsDeleted"}
{"level":"error","ts":1564434749.5986161,"logger":"migration|pvpl4","msg":"","error":"pods \"nginx-deployment-6c7958f7b7-nbctp-stage\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2 spec.initContainers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2 spec.containers[0].securityContext.seLinuxOptions.level: Invalid value: \"s0:c17,c14\": must be s0:c23,c2]","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:302\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:263\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:367\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:76\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}

**Comment by jwmatthews** [comment]
Some related background info

https://docs.openshift.com/container-platform/3.11/install_config/persistent_storage/pod_security_context.html#supplemental-groups

**Comment by Danil-Grigorev** [comment]
After a long investigation, the solution was found. All of the migrated resources, usually have specific annotations in the namespace, which determines the ranges for the selinux context, as well as UID and GID ranges for the specific container. Every pod, which is deployed in the namespace, gathers it's values from there.

During the migration with the restic, a temporary stage pod is needed. The values of the selinux are getting preserved in the pod specification deployed on the source cluster, which leads to same definition of the pod on the target cluster after migration.

Although, the error message, which pops up in the logs, is based on the fact, that the namespace definition on the target cluster contains different ranges then the ones from the stage pod specification. Say for example
```
$ oc get project default -o yaml 
...
metadata:
  annotations: 
    openshift.io/sa.scc.mcs: s0:c8,c2
    openshift.io/sa.scc.supplemental-groups: 1000000000/10000 
    openshift.io/sa.scc.uid-range: 1000000000/10000 
```
for the source cluster, and
```
$ oc get project default -o yaml 
...
metadata:
  annotations: 
    openshift.io/sa.scc.mcs: s0:c23,c7
    openshift.io/sa.scc.supplemental-groups: 1000000000/10000 
    openshift.io/sa.scc.uid-range: 1000000000/10000 
```
for the target, will lead to the cluster not accepting the restore of the pod with values
```
   securityContext:
      fsGroup: 1000480000
      seLinuxOptions:
        level: s0:c8,c2
```
The deployment of such pod will lead to a popup of the error seen in the logs. Same error is displayed in the namespace, when an `oc get events` command is run.

Thanks @dymurray and @djwhatle for pointing out details. The fix for the issue and all related ones #222 will be fixed by the https://github.com/fusor/openshift-migration-plugin/pull/8

**Comment by jwmatthews** [comment]
@dymurray should this be closed, or is there more work to do here?

**Comment by jwmatthews** [comment]
Closing as I believe below addressed the issue
https://github.com/fusor/openshift-migration-plugin/pull/8
