### ISSUE TITLE
Quiesce does not wait for pods to finish terminating

### ISSUE THREAD

**Issue by jmontleon** [fusor/mig-controller#194]
Starting a final migration in the UI after completing a stage migration caused the pod to start terminating with Quiesce Pods: True, however the backup began and actually completed before the pod finished terminating.

On the destination pod the mariadb instance would not start, complaining at a minimum about lock files that exist. 

This was the migmigration that was created:
```
Name:         02939920-a3e0-11e9-a78c-f30556ee7e15
Namespace:    mig
Labels:       <none>
Annotations:  touch=e0b875f2-7cf9-4df6-b311-dd3ea74fad4d
API Version:  migration.openshift.io/v1alpha1
Kind:         MigMigration
Metadata:
  Creation Timestamp:  2019-07-11T13:30:12Z
  Generation:          22
  Resource Version:    5473255
  Self Link:           /apis/migration.openshift.io/v1alpha1/namespaces/mig/migmigrations/02939920-a3e0-11e9-a78c-f30556ee7e15
  UID:                 02b45491-a3e0-11e9-a219-0ed41539d98e
Spec:
  Mig Plan Ref:
    Name:        stage
    Namespace:   mig
  Quiesce Pods:  true
  Stage:         false
Status:
  Conditions:
    Category:              Advisory
    Durable:               true
    Last Transition Time:  2019-07-11T13:32:15Z
    Message:               The migration has completed successfully.
    Reason:                Completed
    Status:                True
    Type:                  Succeeded
  Phase:                   Completed
  Start Timestamp:         2019-07-11T13:30:12Z
Events:                    <none>
```

**Comment by jmontleon** [comment]
Pod state while the backup was running:
```
NAME                    READY     STATUS        RESTARTS   AGE
mariadb-1-7kgxf         1/1       Terminating   0          1h
```

**Comment by jortel** [comment]
Trying to work out _how_ the controller should wait for the pods to terminate.

Few questions:
- Would it be safe to assume that all pods in the namespace have been scaled down by a `deployment` or `deploymentconfig` and thus safe to blindly wait for all pod to terminate?  Could this result in the controller waiting on pods to terminate that were never scaled down?
- Would it be a good idea to wait for only those pods with labels referencing the `deployment` and `deploymentconfig` in the namespace have been terminated?  Are the labels standard and sure to exist?

Looking at the `mysql-persistent` pod, it seems there are labels referencing the `deployment` and `deploymentconfig`.  
```
Labels:             app=mysql
                    deployment=mysql-1
                    deploymentconfig=mysql
                    name=mysql
```

**Comment by sseago** [comment]
I don't believe that we can rely on these labels for all deployments. For deploymentconfigs, those labels will both be there -- hence the mysql example. However, for a deployment (which is not an openstack-specific resource), I don't think we can count on this. For an example of this, look at the velero pod. While velero is controlled by a deployment, there is no `deployment` label created:
```
  labels:
    component: velero
    pod-template-hash: "4010565040"
```

**Comment by sseago** [comment]
Following owner references would be more reliable, but we have to be clear which relationships we're going to traverse, based on which types of resources we're quiescing pods for.
