### ISSUE TITLE
MigMigration can exist without a stage

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-controller#2]
The current `MigMigration` CRD has a stage ref, but migrations can be run without a stage. This should reference a `MigPlan`.

**Comment by djwhatle** [comment]
Plan to solve this by rearranging the references as follows:

```
MigStage:
  MigPlanRef

MigMigration:
  MigPlanRef

```

This should allow MigStage to be run multiple times on the same MigPlan before proceeding to MigMigration. 

After MigMigration has started or is completed for a particular MigPlan, MigStage should not be allowed to run on that plan any more.

**Comment by djwhatle** [comment]
Resolved in #9
