### ISSUE TITLE
"pod volume backup failed: error getting volume path on host: expected one matching path, got 0"

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#207]
Capturing the below so we have it documented in an issue and can come back to see if we can add a preflight check or something to help.   Potential issue for a debugging faq

@sseago saw the below recently on his OCP 3 cluster which was a dev instance, controller was deployed manually and not from mig-operator.

```time="2019-07-19T15:30:49Z" level=error msg="Error backing up item" backup=velero/registry-example-migration-xhvsx error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0" error.file="/go/src/github.com/heptio/velero/pkg/restic/backupper.go:173" error.function="github.com/heptio/velero/pkg/restic.(*backupper).BackupPodVolumes" group=v1 logSource="pkg/backup/resource_backupper.go:269" name=mysql-2-nx2tk-stage namespace=mysql-persistent resource=pods```

@pranavgaikwad suggested the issue relates to
1. restic pod not running as privileged
1. restic volume mount path not patched

Issue ended up being the configuration of the Restic Daemonset

It was:
```
  - hostPath:
          path: /var/lib/kubelet/pods
          type: ""

```

It needs to be:
```
- hostPath:
          path: /var/lib/origin/openshift.local.volumes/pods
```

**Comment by jortel** [comment]
The operator should ensure velero is deployed properly.  Can this be closed, @jwmatthews?

**Comment by sseago** [comment]
I used to hit this when I was installing Velero manually. I haven't seen it using the operator.
