### ISSUE TITLE
Move action should be unavailable if server is inaccessible from destination cluster

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-controller#214]
I was going through the UI and selected `move` for a PV that is using NFS so all is expected to work. The NFS PV was connected to the volume using an internal domain name:
```
  nfs:
    path: /srv/nfs/user-vols/vol113
    server: support1.dymurray-ocp3.internal
```

`support1` node is actually not exposed outside of the `dymurray-ocp3` domain so this PV should only really have copy as a supported action.

This also means the UI needs an additional component to "check connection" of `move` PVs.

**Comment by jwmatthews** [comment]
Just capturing that mig-agnosticd has a setting now that should default to making the support instance use a public dns name
https://github.com/fusor/mig-agnosticd/pull/20

Agree with Dylan that this is something we'd want to address on controller side and agree ga-blocker makes sense and not beta-blocker.
