### ISSUE TITLE
Decouple controller and CRs so they are in separate namespaces

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#220]
We ran into an issue recently of not being able to delete the 'mig' namespace because of finalizers.  We added finalizers to our resources and the controller will remove those on delete, but when executing a delete of 'mig' namespace the controller was killed so it couldn't remove the finalizers on other objects and the namespace was in a terminating state.

Our plan to resolve is to split the controller and data so they are in different namespaces.

I spoke to @shawn-hurley for sanity check on this approach and it makes sense to proceed with

We also discussed if we should use 'openshift-operators' as the namespace we deploy our operator and controllers into or if we should use a different namespace.  Recommendation is we create our own namespace for the controller and operator to run in for now.   Reasoning is that in near future we will likely want to collect metrics and 'openshift-operators' isn't setup for scraping of metrics.

cc @jortel

**Comment by jortel** [comment]
Let's get away from the cryptic `mig` namespace.

Suggest:

`openshift-migration` for:
- migration CRs
- velero CRs

`openshift-migration-operator` for:
- our operator
- our controller.
- velero/restic controllers.

**Comment by sseago** [comment]
By default, Velero/restic controllers and velero CRs live in the same namespace (velero). I don't know that anything actually depends on it, though, as I have accidentally created backups in my app namespace before. So we may be fine separating velero CRs from velero controllers, but I guess we'll know for sure once we start testing with it. I would assume that we will want the migration registry resources to be put in the same namesapce as the velero controller.

**Comment by jortel** [comment]
>  I would assume that we will want the migration registry resources to be put in the same namesapce as the velero controller.

I'm thinking the registry related resources (DC/Service/Pod/Secret) should go in the _openshift-migration_ namespace since they are related to, and created on behalf of, our CRs.  And, because they are deleted by our finalizers.

**Comment by sseago** [comment]
We should also make sure we're clear on which categories of resources go where, as it affects which clusters need which namespaces, although it could be that we're at a point where something from each namespace will be everywhere and it's a non-issue.
Controller clusters: migration CRs, migration controller, operator
Src/Dest clusters: velero CRs and secrets, registry-related resources, velero/restic controllers, operator

**Comment by jwmatthews** [comment]
We ended up going back to a single namespace, closing this issue as we don't intend to split namespaces for now.
