### ISSUE TITLE
Stage pod unable to validate against any SCC during migration

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-controller#228]
From PR #227. It appears something with the DeleteAnnotations function is causing this error to populate. It does not seem related to the changes we are merging in. 

> I am seeing a log statement after the stage restore runs when deleting annotations on the stage resources:
> 
> ```
> {"level":"error","ts":1564518878.9188626,"logger":"migration|t89hk","msg":"","error":"pods \"mariadb-1-jc48w-stage\" is forbidden: unable to validate against any security context constraint: []","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:341\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:297\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:367\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
> ```
> 
> It's something I want to investigate but nothing is broken. The stage pod still ran successfully and restic successfully performs a podvolumerestore. I think it has to do with `deleteAnnotations` or the stage cleanup process.

This came from an investigation into: https://github.com/fusor/mig-controller/issues/191

**Comment by jwmatthews** [comment]
Assigning this as a beta-blocker as I fear the messages will mislead folks testing, if it's possible to find the issue and fix would make a better beta experience.

**Comment by Danil-Grigorev** [comment]
@dymurray @jwmatthews Assuming the stage pod was already deleted, we don't need to touch it's annotations. The annotation change in kubernetes 1.12+ causes pod to be reconciled, and the cluster tries to validate the SCC on the annotations of the pod, which were removed at this point. I noticed that the error happens right after the log message about stage pod is removal. What is the course of action here? Skipping deleted pods might be enough?

Here is a snip from the logs:
```
{"level":"info","ts":1565007430.6335168,"logger":"migration|qmz6q","msg":"Pod annotations/labels added.","ns":"mysql-persistent-test-move","name":"mysql-1-cmsqs"}
{"level":"info","ts":1565007431.0338788,"logger":"migration|lw5pz","msg":"Stage pod created.","ns":"mysql-persistent-test-move","name":"mysql-1-cmsqs-stage"}
{"level":"info","ts":1565007546.1937892,"logger":"migration|wz5bl","msg":"Stage pod deleted.","ns":"mysql-persistent-test-move","name":"mysql-1-cmsqs-stage"}
{"level":"info","ts":1565007546.2349448,"logger":"migration|wz5bl","msg":"Stage pod deleted.","ns":"mysql-persistent-test-move","name":"mysql-1-cmsqs-stage"}
{"level":"info","ts":1565007546.8337853,"logger":"migration|qtbgl","msg":"Pod annotations/labels removed.","ns":"mysql-persistent-test-move","name":"mysql-1-cmsqs-stage"}
{"level":"error","ts":1565007546.8559673,"logger":"migration|qtbgl","msg":"","error":"pods \"mysql-1-cmsqs-stage\" is forbidden: unable to validate against any security context constraint: []","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deletePodAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:349\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).deleteAnnotations\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/annotation.go:301\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:367\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:77\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:168\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

**Comment by dymurray** [comment]
@Danil-Grigorev Thanks for that write-up, yeah I believe you are correct. I will look into this today and hopefully find an easy fix.

**Comment by dymurray** [comment]
Reopening as it appears this is still a reported issue, even sometimes during `EnsureStageRestore` phase as I observed on @jwmatthews environment. I also hit this with the `latest` controller image. Will speak with Danil to get a fix.

**Comment by dymurray** [comment]
Danil mentioned we shouldn't be deleting annotations of stage pods just to delete them, and he is correct. So the solution is easy to just delete stage pods before removing all the annotations/labels on a failure cleanup.
