### ISSUE TITLE
Fix controller to support non-AWS S3 providers such as Minio or NooBaa

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#230]
Today we attempted to configure a MigStorage object with just an `awsS3Url` as the target coordinates, and found that mig-controller rejected our input with a validation critical condition, requesting that we provide an S3 bucket name and region. 

Providing a region and S3 bucket name results in an amazonaws S3 URL being constructed, and the provided `awsS3Url` field being ignored.

We should also be removing `aws` fields from migstorage and instead be referring to these fields as `s3`.

**Comment by jwmatthews** [comment]
Let's ensure we test with:

- NooBaa
- Minio
- AWS S3

**Comment by jortel** [comment]
The only s3 `BackupStorageProvider` we currently support by name is `aws`.  Seems like we need to expand supported values to include: `minio` and `noobaa`.

**Comment by djwhatle** [comment]
@jortel yeah may be worth having a discussion on how to handle this. Our usage of `AWS` to be the BSL 'type' for any S3-compatible storage came from the convention set by Velero. 

https://github.com/heptio/velero/blob/master/site/docs/master/api-types/backupstoragelocation.md#aws

Since we are just dumping part of our MigStorage content into a Velero BSL it made sense to me to stick close to their terminology to minimize confusion. Could be there's a better solution.

**Comment by jortel** [comment]
To minimize impact on the UI, we may want to take a short-term approach of documenting the _correct_ settings to be used for `minio` and `noobaa` in the existing CR.  

Long term, we should consider re-modeling the CR so that the provider _type_ is explicit with specific properties.  Issue #239 is intended to capture the discussion and design.

**Comment by dymurray** [comment]
This is fixed as of #261
