### ISSUE TITLE
Controller needs to support Velero Snapshots when appropiate

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-controller#256]
Currently when a user selects copy we are always defaulting to using Restic to perform the PV migration. We need the ability to intelligently detect when we are migrating a PV that could be restored via cloud-native snapshot tool that Velero uses. An example of this is if I want to migrate an application that is using an EBS volume in region `us-east-1`. If my OCP4 cluster is running with a storage class that points to EBS and region `us-east-1` then we do not want to use restic, but rather use Velero's native support for cloud-based volume snapshots. This means if we detect `copy` and a storage class that supports snapshots, we do *not* add restic annotations.

**Comment by dymurray** [comment]
Adding `beta-blocker` label in case we have time to solve this for beta.

**Comment by sseago** [comment]
So upon some initial investigation, it seems that the biggest challenge is that for EBS at least, we don't really have an obvious way to know what region the dest cluster is using, which means we can't figure out automatically whether the volume can be copied via snapshots. One possibility is to add an explicit UI checkbox/API flag along with the dest storageclass selection, which we will only offer if src storageclass and selected dest storageclass have "kubernetes.io/aws-ebs" as the provisioner. For azure/GCP support we could do the same.

**Comment by sseago** [comment]
Controller support for this was added with https://github.com/fusor/mig-controller/pull/288
