### ISSUE TITLE
Ensure that URLs specified for BackupStorageLocations: 'must be valid according to https://golang.org/pkg/net/url/#Parse and start with http:// or https://'

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#269]
Attempted to use minio for BSL, I entered the 'route' as I got it from 'oc get routes'.
Forgot to enter 'https://'.

Check Connection from UI returned success.

When I attempted to Stage and do a Backup I saw below failure from Velero logs.

`time="2019-08-15T23:22:26Z" level=error msg="Error getting backup store for this location" backupLocation=minio-n49g5 controller=backup-sync error="rpc error: code = Unknown desc = Invalid s3 url minio-gpte-minio.apps.cluster-jwm0815ocp4a.jwm0815ocp4a.mg.dog8code.com, URL must be valid according to https://golang.org/pkg/net/url/#Parse and start with http:// or https://" error.file="/go/src/github.com/heptio/velero/pkg/cloudprovider/aws/object_store.go:170" error.function=github.com/heptio/velero/pkg/cloudprovider/aws.newAWSConfig logSource="pkg/controller/backup_sync_controller.go:168"
`

**Comment by jortel** [comment]
Let's add a validation for URLs.
