### ISSUE TITLE
Autogenerated RBAC should assign permissions to 'migration-controller' SA instead of 'default'

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#273]
https://github.com/fusor/mig-operator/pull/42

Most likely need to fix this in the kustomize configuration.

Until we fix this we have to manually tweak RBAC every time we copy updates in manifests over to mig-operator.

**Comment by jortel** [comment]
@djwhatle Can this be closed?

**Comment by djwhatle** [comment]
@jortel the autogenerated RBAC appears to point to the ServiceAccount `""` in the ClusterRoleBinding. Not sure what the behavior of binding to `""` is, perhaps this binds to default, but regardless seems the auto-generated RBAC isn't pointing at the `migration-controller` SA.

https://github.com/fusor/mig-controller/blob/master/config/rbac/manager_role_binding.yaml

It looks like this is being manually patched into the ClusterRoleBinding YAML deployed by the operator:

https://github.com/fusor/mig-operator/blob/master/roles/migrationcontroller/templates/mig_rbac.yml.j2#L307-L319
