### ISSUE TITLE
Add a health check during creation of MigPlan to show unhealthy/unready pods

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#286]
Prior to running a migration we should have an idea of the state of the namespaces selected in the Migration Plan.

Let's consider having the controller watch those namespaces and update the MigPlan CR with the state of the existing pods.

Thinking for first phase we add this for pods in every namespace, we look for their condition and update CR.   Was thinking we update with all pod found so that the UI has information so it can display on the validation screen for a MigPlan that ~20 pods are in a good state and one is unhealthy or similar.

**Comment by dymurray** [comment]
Fixed. Closing.
