### ISSUE TITLE
Add a health check after a 'migrate' has completed.

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#287]
Similar to https://github.com/fusor/mig-controller/issues/286 we want to add a check of all pods and capture status after a migration has occurred.

Concerned about capturing info for case of migrating 'robot-shop' as of today.

robot-shop looks to migrate successfully from our status and from looking at the webui of robot-shop. yet one of the pods failed to run to setup mysql: https://github.com/fusor/mig-demo-apps/issues/8

Looking for ability for UI/API to show:
 - We completed the migration, from our side things are looked good
 - We looked at the associated namespaces, and from the pods running we do see what looks like a problem, see that "this pod X is in state Y, here are the associated events", link to openshift-console for this specific pod to debug more

**Comment by dymurray** [comment]
https://github.com/fusor/mig-controller/pull/321
