### ISSUE TITLE
Bug 1747471 - Backup/migration should fail sooner - 125 namespaces

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#297]
https://bugzilla.redhat.com/show_bug.cgi?id=1747471

**Comment by jwmatthews** [comment]
Aligning as a potential GA Blocker, this has potential to be less ga blocker and more an issue to address in z-stream update during 4.2 cycle.

**Comment by mansam** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1747471 has been closed.
