### ISSUE TITLE
Add IsHostCluster to MigCluster CRD

### ISSUE THREAD

**Issue by eriknelson** [fusor/mig-controller#5]
Through slack discussion, it became clear that we need something to create a `MigCluster` that represents the cluster hosting the controller + the UI. Both will need to be able to distinguish it from `MigCluster` objects that have been added by users, because it should be immutable in the UI, and the controller will construct a client for this cluster differently than if it were a user added cluster with an associated ServiceAccount token. We settled on a few conclusions:

1) It will be the "migration operator's" responsibility to ensure that a `MigCluster` representing the host cluster is created during installation, which should be considered immutable (the operator will enforce it exists unchanged).

2) We should add an `IsHostCluster` boolean field to the `MigCluster` CRD that will act as a flag. The controller should validate only one of these exists in a Ready state at any given time, and it should default to false.

**Comment by eriknelson** [comment]
Does it make sense to actually have the clusterRef and serviceAccountSecretRef both be optional? Neither would be used in the host cluster's case.

**Comment by djwhatle** [comment]
I think it would make sense to have an `IsHostCluster` bool, and to make `clusterRef` and `serviceAccountSecretRef` optional since we will always have access to the local cluster config from inside of the controller.

**Comment by djwhatle** [comment]
Resolved in #9
