### ISSUE TITLE
Break out plan validation logic to a common pkg

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-controller#50]
Since the `MigStage` and `MigMigration` objects share a need to validate planRefs, we should break out the Plan validation to a common package.

We should change https://github.com/fusor/mig-controller/blob/master/pkg/controller/migmigration/validation.go#L63 to take a `MigPlanRef` as an input and have a common `validation` pkg.

**Comment by jortel** [comment]
@dymurray This can be closed, right?

**Comment by dymurray** [comment]
Yes thanks!
