### ISSUE TITLE
Handle Velero delay in noticing changes to BSL/VSL and secrets

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#84]

**Comment by jortel** [comment]
Related to: #188

**Comment by jwmatthews** [comment]
Ran into this tonight.

My workflow was:
1. Create a MigStorage with credentials that lacked access to work with EBS Volumes, so I received an error on validation from MigStorage
2. I created a new IAM account and added to MigStorage
3. I saw MigStorage go 'Green' within seconds then I attempted a Stage of MSSQL
4. After a minute or so I saw 'Backup: mig/708c67e0-b26d-11e9-930d-5d401ce49ef2-7kz8l partially failed.'

When I looked at the 'backup CRs' on the source cluster I noticed several backup CRs from prior runs from S3 storage.  

'My' backup CR for this last operation as about 1 minute older than the other CRs that were recreated by my S3 storage.  It looks like what happened is that my backup CR was created before the cloud-credentials were refreshed by Velero, so my backup before Velero was ready, then after my backup failed, the cloud credentials were refreshed.


Looking at the related backup CR on source
```
$ oc get backup 708c67e0-b26d-11e9-930d-5d401ce49ef2-7kz8l -n mig -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  annotations:
    openshift.io/migrate-copy-phase: stage
    openshift.io/migration-registry: 172.30.6.219:5000
    openshift.io/migration-registry-dir: /test01-registry-a865b483-b26b-11e9-be86-0ad7604b88d6
  creationTimestamp: "2019-07-30T01:58:13Z"
  generateName: 708c67e0-b26d-11e9-930d-5d401ce49ef2-
  generation: 1
  labels:
    app.kubernetes.io/part-of: migration
    migmigration: 70a8e472-b26d-11e9-be86-0ad7604b88d6
    migration-stage-backup: 70a8e472-b26d-11e9-be86-0ad7604b88d6
    velero.io/storage-location: jwms3-v5x7x
  name: 708c67e0-b26d-11e9-930d-5d401ce49ef2-7kz8l
  namespace: mig
  resourceVersion: "50148"
  selfLink: /apis/velero.io/v1/namespaces/mig/backups/708c67e0-b26d-11e9-930d-5d401ce49ef2-7kz8l
  uid: 7d36849b-b26d-11e9-b46b-0a003cad64ac
spec:
  excludedNamespaces: []
  excludedResources: []
  hooks:
    resources: []
  includeClusterResources: null
  includedNamespaces:
  - mssql-persistent
  includedResources:
  - persistentvolumes
  - persistentvolumeclaims
  - imagestreams
  - imagestreamtags
  - secrets
  - configmaps
  - pods
  labelSelector:
    matchLabels:
      migration-included-stage-backup: 70a8e472-b26d-11e9-be86-0ad7604b88d6
  storageLocation: jwms3-v5x7x
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - jwms3-7d9l9
status:
  completionTimestamp: null
  errors: 0
  expiration: "2019-08-29T01:58:13Z"
  phase: Failed
  startTimestamp: "2019-07-30T01:58:13Z"
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0
  warnings: 0
```


Looking at velero pod logs

```
time="2019-07-30T01:58:13Z" level=error msg="backup failed" controller=backup error="rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" error.file="/go/src/github.com/heptio/velero/pkg/cloudprovider/aws/volume_snapshotter.go:58" error.function=github.com/heptio/velero/pkg/cloudprovider/aws.getSession key=mig/708c67e0-b26d-11e9-930d-5d401ce49ef2-7kz8l logSource="pkg/controller/backup_controller.go:230"
time="2019-07-30T01:58:23Z" level=error msg="Error getting backup store for location" backupLocation=jwms3-v5x7x controller=backup-sync error="rpc error: code = Unknown desc = NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors" error.file="/go/src/github.com/heptio/velero/pkg/cloudprovider/aws/volume_snapshotter.go:58" error.function=github.com/heptio/velero/pkg/cloudprovider/aws.getSession logSource="pkg/controller/backup_sync_controller.go:162"
time="2019-07-30T01:59:24Z" level=info msg="Syncing contents of backup store into cluster" backupLocation=jwms3-v5x7x controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:170"
time="2019-07-30T01:59:24Z" level=info msg="Got backups from backup store" backupCount=25 backupLocation=jwms3-v5x7x controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:17
```

**Comment by fbladilo** [comment]
@jwmatthews This issue can be reproduced every time with any migration, the only condition is to start with new fresh controllers, create a migplan and right after a migmigration. Velero does not pick up the cloud credentials in time and fails with that message, any other migration after that, velero is fine. This is a typical CI flow, we destroy/re-create controllers and we had to implement a pause of 120 seconds to be safe during the very first backup.

**Comment by jortel** [comment]
The appropriate fix would be to submit a patch to velero (or fix in our fork) to _watch_ the secret and act accordingly when it changes.

**Comment by alexander-demichev** [comment]
@jwmatthews @jortel The issue is on kubernetes side, there is a delay from the moment  when secret is updated to moment where mounted file is injected into pod.
`
As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period (1 minute by default) + ttl of ConfigMaps cache (1 minute by default) in kubelet.
`
https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically

**Comment by jwmatthews** [comment]
@alexander-demichev has a proposal to address, tracking in Velero repo in below issue:

https://github.com/heptio/velero/issues/1824


This will not be fixed by beta, removing beta-blocker.

I am doubtful this will be fixed for ga-blocker, but aligned to ga-blocker for now to be sure we at least address this in docs.
