### ISSUE TITLE
Add ability to detect errors in Stage or Migrate and report back to Custom Resource

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#85]

**Comment by jortel** [comment]
https://github.com/fusor/mig-controller/pull/136

**Comment by jortel** [comment]
@jwmatthews I think this issue is resolved. Do you think https://github.com/fusor/mig-controller/pull/136 is sufficient to close this issue?

**Comment by jwmatthews** [comment]
@jortel looks good, I see you have coverage of Velero Backup and Restore failing, that was the main ask for first phase of error detection.  

We will track integration in webui via https://github.com/fusor/mig-ui/issues/243

**Comment by jortel** [comment]
Fixed by: https://github.com/fusor/mig-controller/pull/136
