### ISSUE TITLE
Add Azure and GCP support to Cloud Providers for BSL/VSL

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#89]
Need to confirm our API can handle Azure configuration along with S3 and test compatibility with velero.

**Comment by jwmatthews** [comment]
I am marking this as a beta-blocker as I believe support for Azure will be desired for OCP 4.2.   Assuming we will want to support use cases of migrations between cloud providers.

**Comment by dymurray** [comment]
Closing as GCP/Azure support has been merged.
